arch: "resnet18"
pretrained: true

data_folder: ./data/food-101
batch_size: 64
epochs: 10
lr: 3e-4
weight_decay: 0.01
num_workers: 4
freeze_backbone: false
device: cuda
seed: 3

mlflow: true
mlflow_experiment: "Image-Classification"
mlflow_tracking_uri: "file:./mlruns"
mlflow_tags:
  dataset: "food101"
  stage: "dev"
